token:
    auth:
        expiry: '24h'
        revoke_existing: false
    verification:
        expiry: '24h'
        revoke_existing: true
    password_reset:
        expiry: '1h'
        revoke_existing: true
verification: true # When false, users can login without verifying their email
redirect_urls:
    verification: 'https://example.com/verify'
    password_reset: 'https://example.com/reset'
allow:
    # password_reset: true
    concurrent_logins: true # When false, previous tokens are revoked on login
password_strength:
    min_length: 8
    max_length: 128
    require_uppercase: false
    require_lowercase: false
    require_numbers: false
    require_special: false
