tokens:
    access_token:
        expiry: '15m' # Short-lived JWT access tokens
        type: 'jwt' # JWT (stateless) vs 'database' (stateful)
    refresh_token:
        expiry: '168h' # Long-lived refresh tokens (7 days = 168 hours)
        type: 'database' # Stored in database for revocation
        revoke_existing: false # Allow multiple concurrent sessions
    email_verification:
        expiry: '24h' # Email verification tokens
        type: 'database' # Stored in database
        revoke_existing: true # Only one verification token at a time
    password_reset:
        expiry: '1h' # Password reset tokens
        type: 'database' # Stored in database
        revoke_existing: true # Only one reset token at a time
verification: true # When false, users can login without verifying their email
redirect_urls:
    verification: 'https://example.com/verify'
    password_reset: 'https://example.com/reset'
allow:
    # password_reset: true
    concurrent_logins: true # When false, previous tokens are revoked on login
password_strength:
    min_length: 8
    max_length: 128
    require_uppercase: false
    require_lowercase: false
    require_numbers: false
    require_special: false
