auth:
    enabled: false
    header:
        key: '' # Ex. 'Authorization'
        value: '' # Ex. 'Bearer TOKEN'
from: '' # Ex. 'noreply@example.com'
templates:
    verification: 'verify-email' # Template name for email verification
    reset: 'reset-password' # Template name for password reset
subjects:
    verification: 'Verify your email: {{.email}}'
    reset: 'Password reset for: {{.email}}'
